### ISSUE TITLE
Error after run create dataset

### ISSUE THREAD

**Issue by XanYder** [ardamavi/Game-Bot#1]
This is my anaconda log when I run create dataset and I press "a":

(base) C:\Users\Xander>python "D:\Game-Bot-master\Game-Bot-master\create_dataset.py"
D:\Anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
D:\Anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "D:\Game-Bot-master\Game-Bot-master\create_dataset.py", line 76, in <module>
    main()
  File "D:\Game-Bot-master\Game-Bot-master\create_dataset.py", line 72, in main
    listen_keyboard()
  File "D:\Game-Bot-master\Game-Bot-master\create_dataset.py", line 63, in listen_keyboard
    listener.join()
  File "D:\Anaconda\lib\site-packages\pynput\_util\__init__.py", line 185, in join
    six.reraise(exc_type, exc_value, exc_traceback)
  File "D:\Anaconda\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "D:\Anaconda\lib\site-packages\pynput\_util\__init__.py", line 140, in inner
    return f(self, *args, **kwargs)
  File "D:\Anaconda\lib\site-packages\pynput\keyboard\_win32.py", line 237, in _process
    self.on_press(key)
  File "D:\Anaconda\lib\site-packages\pynput\_util\__init__.py", line 71, in inner
    if f(*args) is False:
  File "D:\Game-Bot-master\Game-Bot-master\create_dataset.py", line 57, in on_press
    save_event_keyboard(data_path, 1, key)
  File "D:\Game-Bot-master\Game-Bot-master\create_dataset.py", line 25, in save_event_keyboard
    key = get_id(key)
  File "D:\Game-Bot-master\Game-Bot-master\game_control.py", line 13, in get_id
    return get_keys().index(key)
ValueError: 'a' is not in list
Process Process-1:
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\pynput\_util\win32.py", line 375, in _handler
    converted = self._convert(code, msg, lpdata)
  File "D:\Anaconda\lib\site-packages\pynput\_util\win32.py", line 387, in _convert
    raise NotImplementedError()
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\Anaconda\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Game-Bot-master\Game-Bot-master\create_dataset.py", line 49, in listen_mouse
    listener.join()
  File "D:\Anaconda\lib\site-packages\pynput\_util\__init__.py", line 185, in join
    six.reraise(exc_type, exc_value, exc_traceback)
  File "D:\Anaconda\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "D:\Anaconda\lib\site-packages\pynput\_util\__init__.py", line 140, in inner
    return f(self, *args, **kwargs)
  File "D:\Anaconda\lib\site-packages\pynput\_util\win32.py", line 379, in _handler
    self._handle(code, msg, lpdata)
  File "D:\Anaconda\lib\site-packages\pynput\mouse\_win32.py", line 186, in _handle
    self.on_click(data.pt.x, data.pt.y, button, pressed)
  File "D:\Anaconda\lib\site-packages\pynput\_util\__init__.py", line 71, in inner
    if f(*args) is False:
  File "D:\Game-Bot-master\Game-Bot-master\create_dataset.py", line 43, in on_click
    save_event_mouse(data_path, x, y)
  File "D:\Game-Bot-master\Game-Bot-master\create_dataset.py", line 34, in save_event_mouse
    save_img(data_path, screenshot)
  File "D:\Game-Bot-master\Game-Bot-master\get_dataset.py", line 15, in save_img
    imsave(path, img)
  File "D:\Anaconda\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "D:\Anaconda\lib\site-packages\scipy\misc\pilutil.py", line 217, in imsave
    im = toimage(arr, channel_axis=2)
  File "D:\Anaconda\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "D:\Anaconda\lib\site-packages\scipy\misc\pilutil.py", line 327, in toimage
    raise ValueError("'arr' does not have a suitable array shape for "
ValueError: 'arr' does not have a suitable array shape for any mode.

**Comment by A-Charvin** [comment]
Update h5py of conda with this.
`conda update h5py`
