### ISSUE TITLE
Hmm its to long

### ISSUE THREAD

**Issue by NakyMC** [ardamavi/Game-Bot#12]
Hi there
Basicly i couldn't make tensorflow work on 3.6.0 so i decided to use miniconda (with nevest wersion of python) and then i was able to make it running.
my steps:
-instaling miniconda
-installed numpy 
-instaled tensorflow
-tried arround PIL and realised that it works on 2.7 
-googled this --force html5lib  -> pip install Pillow
-then I looked at your site and I realized that you proved file with packages so what i did was 
pip install -r requirements.txt 
and there is the final as tensorflow was able to run i tried to create data set and this is list of errors that is gave me

Using TensorFlow backend.
Using TensorFlow backend.
Unhandled exception in listener callback
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\pynput\_util\win32.py", line 375, in _handler
    converted = self._convert(code, msg, lpdata)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pynput\_util\win32.py", line 390, in _convert
    raise NotImplementedError()
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\pynput\_util\__init__.py", line 157, in inner
    return f(self, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pynput\_util\win32.py", line 379, in _handler
    self._handle(code, msg, lpdata)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pynput\mouse\_win32.py", line 190, in _handle
    self.on_click(data.pt.x, data.pt.y, button, pressed)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pynput\_util\__init__.py", line 78, in inner
    if f(*args) is False:
  File "C:\Users\mchin\Downloads\Game-Bot-master\create_dataset.py", line 43, in on_click
    save_event_mouse(data_path, x, y)
  File "C:\Users\mchin\Downloads\Game-Bot-master\create_dataset.py", line 34, in save_event_mouse
    save_img(data_path, screenshot)
  File "C:\Users\mchin\Downloads\Game-Bot-master\get_dataset.py", line 15, in save_img
    imsave(path, img)
  File "C:\ProgramData\Miniconda3\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "C:\ProgramData\Miniconda3\lib\site-packages\scipy\misc\pilutil.py", line 217, in imsave
    im = toimage(arr, channel_axis=2)
  File "C:\ProgramData\Miniconda3\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "C:\ProgramData\Miniconda3\lib\site-packages\scipy\misc\pilutil.py", line 327, in toimage
    raise ValueError("'arr' does not have a suitable array shape for "
ValueError: 'arr' does not have a suitable array shape for any mode.
Process Process-1:
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\pynput\_util\win32.py", line 375, in _handler
    converted = self._convert(code, msg, lpdata)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pynput\_util\win32.py", line 390, in _convert
    raise NotImplementedError()
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\ProgramData\Miniconda3\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\mchin\Downloads\Game-Bot-master\create_dataset.py", line 52, in listen_mouse
    listener.join()
  File "C:\ProgramData\Miniconda3\lib\site-packages\pynput\_util\__init__.py", line 205, in join
    six.reraise(exc_type, exc_value, exc_traceback)
  File "C:\ProgramData\Miniconda3\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pynput\_util\__init__.py", line 157, in inner
    return f(self, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pynput\_util\win32.py", line 379, in _handler
    self._handle(code, msg, lpdata)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pynput\mouse\_win32.py", line 190, in _handle
    self.on_click(data.pt.x, data.pt.y, button, pressed)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pynput\_util\__init__.py", line 78, in inner
    if f(*args) is False:
  File "C:\Users\mchin\Downloads\Game-Bot-master\create_dataset.py", line 43, in on_click
    save_event_mouse(data_path, x, y)
  File "C:\Users\mchin\Downloads\Game-Bot-master\create_dataset.py", line 34, in save_event_mouse
    save_img(data_path, screenshot)
  File "C:\Users\mchin\Downloads\Game-Bot-master\get_dataset.py", line 15, in save_img
    imsave(path, img)
  File "C:\ProgramData\Miniconda3\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "C:\ProgramData\Miniconda3\lib\site-packages\scipy\misc\pilutil.py", line 217, in imsave
    im = toimage(arr, channel_axis=2)
  File "C:\ProgramData\Miniconda3\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "C:\ProgramData\Miniconda3\lib\site-packages\scipy\misc\pilutil.py", line 327, in toimage
    raise ValueError("'arr' does not have a suitable array shape for "
ValueError: 'arr' does not have a suitable array shape for any mode.
Unhandled exception in listener callback
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\pynput\_util\__init__.py", line 157, in inner
    return f(self, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pynput\keyboard\_win32.py", line 240, in _process
    self.on_press(key)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pynput\_util\__init__.py", line 78, in inner
    if f(*args) is False:
  File "create_dataset.py", line 60, in on_press
    save_event_keyboard(data_path, 1, key)
  File "create_dataset.py", line 25, in save_event_keyboard
    key = get_id(key)
  File "C:\Users\mchin\Downloads\Game-Bot-master\game_control.py", line 13, in get_id
    return get_keys().index(key)
ValueError: 'p' is not in list
Traceback (most recent call last):
  File "create_dataset.py", line 79, in <module>
    main()
  File "create_dataset.py", line 75, in main
    listen_keyboard()
  File "create_dataset.py", line 66, in listen_keyboard
    listener.join()
  File "C:\ProgramData\Miniconda3\lib\site-packages\pynput\_util\__init__.py", line 205, in join
    six.reraise(exc_type, exc_value, exc_traceback)
  File "C:\ProgramData\Miniconda3\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pynput\_util\__init__.py", line 157, in inner
    return f(self, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pynput\keyboard\_win32.py", line 240, in _process
    self.on_press(key)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pynput\_util\__init__.py", line 78, in inner
    if f(*args) is False:
  File "create_dataset.py", line 60, in on_press
    save_event_keyboard(data_path, 1, key)
  File "create_dataset.py", line 25, in save_event_keyboard
    key = get_id(key)
  File "C:\Users\mchin\Downloads\Game-Bot-master\game_control.py", line 13, in get_id
    return get_keys().index(key)

I have no idee how to make this program runing please help me solve this

**Comment by yarodevuci** [comment]
same here... @NakyMC did u figured it out?

**Comment by breadbrowser** [comment]
what error did you get?
