### ISSUE TITLE
Many Errors

### ISSUE THREAD

**Issue by ShuterLive** [ardamavi/Game-Bot#22]
C:\Program Files\Python36>python3 create_dataset.py

C:\Program Files\Python36>create_dataset.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Program Files\Python36\create_dataset.py", line 12, in <module>
    from get_dataset import save_img
  File "C:\Program Files\Python36\get_dataset.py", line 4, in <module>
    from keras.utils import to_categorical
  File "C:\Program Files\Python36\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Program Files\Python36\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Program Files\Python36\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Program Files\Python36\lib\site-packages\keras\backend\__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "C:\Program Files\Python36\lib\site-packages\keras\backend\load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "C:\Program Files\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Users\ShuterLive\AppData\Roaming\Python\Python36\site-packages\tensorflow\__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "C:\Users\ShuterLive\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\ShuterLive\AppData\Roaming\Python\Python36\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\ShuterLive\AppData\Roaming\Python\Python36\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Program Files\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\ShuterLive\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\ShuterLive\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\core\framework\graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "c:\users\shuterlive\appdata\roaming\python\python36\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: Nie można odnaleźć określonej procedury.

**Comment by jenslilleman** [comment]
i have the same problem.. got it to work?
