### ISSUE TITLE
some keys wont work

### ISSUE THREAD

**Issue by jenslilleman** [ardamavi/Game-Bot#24]
i have finnaly got some keys to work, as you can see, a-z works and 1-0 but ctrl or space or those wont work.
that results in when i want to stop create_dataset (ctrl+C) i just get an error and it freezes..
any help please?

Using TensorFlow backend.
Using TensorFlow backend.
Key Pressed:a
Key Pressed:a
Key Pressed:b
Key Pressed:b
Key Pressed:c
Key Pressed:c
Key Pressed:d
Key Pressed:d
Key Pressed:e
Key Pressed:e
Key Pressed:f
Key Pressed:f
Key Pressed:g
Key Pressed:g
Key Pressed:h
Key Pressed:h
Key Pressed:i
Key Pressed:i
Key Pressed:j
Key Pressed:j
Key Pressed:k
Key Pressed:k
Key Pressed:l
Key Pressed:l
Key Pressed:m
Key Pressed:m
Key Pressed:n
Key Pressed:n
Key Pressed:o
Key Pressed:o
Key Pressed:p
Key Pressed:p
Key Pressed:q
Key Pressed:q
Key Pressed:r
Key Pressed:r
Key Pressed:s
Key Pressed:s
Key Pressed:t
Key Pressed:t
Key Pressed:u
Key Pressed:u
Key Pressed:v
Key Pressed:v
Key Pressed:w
Key Pressed:w
Key Pressed:x
Key Pressed:x
Key Pressed:y
Key Pressed:y
Key Pressed:z
Key Pressed:z
Key Pressed:1
Key Pressed:1
Key Pressed:2
Key Pressed:2
Key Pressed:3
Key Pressed:3
Key Pressed:4
Key Pressed:4
Key Pressed:5
Key Pressed:5
Key Pressed:6
Key Pressed:6
Key Pressed:7
Key Pressed:7
Key Pressed:8
Key Pressed:8
Key Pressed:9
Key Pressed:9
Key Pressed:0
Key Pressed:0
Key Pressed:+
Key Pressed:+
Key Pressed:´
Traceback (most recent call last):
  File "create_dataset.py", line 78, in <module>
    main()
  File "create_dataset.py", line 74, in main
    listen_keyboard()
  File "create_dataset.py", line 65, in listen_keyboard
    listener.join()
  File "C:\Users\jensl\AppData\Local\Programs\Python\Python36\lib\site-packages\pynput\_util\__init__.py", line 185, in join
    six.reraise(exc_type, exc_value, exc_traceback)
  File "C:\Users\jensl\AppData\Local\Programs\Python\Python36\lib\site-packages\six.py", line 695, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\jensl\AppData\Local\Programs\Python\Python36\lib\site-packages\pynput\_util\__init__.py", line 140, in inner
    return f(self, *args, **kwargs)
  File "C:\Users\jensl\AppData\Local\Programs\Python\Python36\lib\site-packages\pynput\keyboard\_win32.py", line 222, in _process
    self.on_press(key)
  File "C:\Users\jensl\AppData\Local\Programs\Python\Python36\lib\site-packages\pynput\_util\__init__.py", line 71, in inner
    if f(*args) is False:
  File "create_dataset.py", line 59, in on_press
    save_event_keyboard(data_path, 1, key)
  File "create_dataset.py", line 24, in save_event_keyboard
    key = get_id(key)
  File "c:\bot\game_control.py", line 14, in get_id
    return get_keys().index(key.char)
ValueError: '´' is not in list

**Comment by tdogtt10** [comment]
##Do you mind sharing the versions or updates that you made?

I ended up getting to probably the same point as you.  I have this capturing my game and taking screen shots but many keys and clicks aren't being reported.

**Comment by jenslilleman** [comment]
i havent got any longer, the problem is when i want stop create_dataset (ctrl+c) it freezes and i dont get anything to train.. if you got it to work please tell me. sorry for late respond
