### ISSUE TITLE
Error in create_dataset.py

### ISSUE THREAD

**Issue by yellowface7** [ardamavi/Game-Bot#26]
So I was following the instructions as shown in the readme but it gave me the following error:

`Traceback (most recent call last):
  File "create_dataset.py", line 7, in <module>
    from PIL import ImageGrab
ModuleNotFoundError: No module named 'PIL'`

One of the modules fail to install when running the install command.

Hope this gets worked out, I really wanted to toy around with this thing. :/

UPDATE: I ran the install command again, which returned the same error but this time when I run the create dataset program, it spits out this peculiar error  `Traceback (most recent call last):
  File "create_dataset.py", line 8, in <module>
    from game_control import *
  File "C:\Users\REDACTED\Game-Bot\game_control.py", line 2, in <module>
    from pynput.mouse import Button, Controller as Mouse
ModuleNotFoundError: No module named 'pynput'`

**Comment by gamingofficeyt** [comment]
you need install the requirements with 

pip install -r requirements.txt

Make sure youre in your correct directory in cmd
