### ISSUE TITLE
ImportError: cannot import name 'imresize' from 'scipy.misc'

### ISSUE THREAD

**Issue by waheedullahkhan001** [ardamavi/Game-Bot#29]
I downloaded the code as zip. I had latest python 3 version. I did `pip3 install -r requirements.txt` it installed all.
but when I ran this command `python3 create_dataset.py` it gave me this error:

```
Traceback (most recent call last):
  File "create_dataset.py", line 9, in <module>
    from predict import predict
  File "C:\Users\admin\Desktop\Game-Bot-master\Game-Bot-master\predict.py", line 3, in <module>
    from scipy.misc import imresize
ImportError: cannot import name 'imresize' from 'scipy.misc' (C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\scipy\misc\__init__.py)
```

after that I simply installed the recommended version from the given link in README.md same error

**Comment by SamuelJMiller** [comment]
I looked through the requirements.txt file, and I didn't see the scipy module specified. Perhaps we need to specify that in the requirements file?

**Comment by EARider23** [comment]
yeah i encounter this same error i dont know how to open it. Solve this Problem ASAP..

**Comment by lostgoldplayer** [comment]
i fixed it

**Comment by breadbrowser** [comment]
pip install scipy==1.1.0 --user

**Comment by SandorAlbert** [comment]
Also it's important to mention that CUDA should be installed since not accessing to the GPU will slow down your program by >10x
