### ISSUE TITLE
Traceback (most recent call last):   File "C:\Users\OneDrive\Desktop\Game-Bot-master\Game-Bot-master\train.py", line 4, in <module>     from get_dataset import get_dataset   File "C:\Users\OneDrive\Desktop\Game-Bot-master\Game-Bot-master\get_dataset.py", line 4, in <module>     from keras.utils import to_categorical ImportError: cannot import name 'to_categorical' from 'keras.utils' (C:\Users\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\keras\utils\__init__.py)   ------------------ (program exited with code: 1)  Press any key to continue . . .

### ISSUE THREAD

**Issue by kuba33k** [ardamavi/Game-Bot#37]
Traceback (most recent call last):   File "C:\Users\OneDrive\Desktop\Game-Bot-master\Game-Bot-master\train.py", line 4, in <module>     from get_dataset import get_dataset   File "C:\Users\OneDrive\Desktop\Game-Bot-master\Game-Bot-master\get_dataset.py", line 4, in <module>     from keras.utils import to_categorical ImportError: cannot import name 'to_categorical' from 'keras.utils' (C:\Users\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\keras\utils\__init__.py)   ------------------ (program exited with code: 1)  Press any key to continue . . .

Can any one help

**Comment by px1club** [comment]
replace that line with "from tensorflow.keras.utils import to_categorical"
