### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'Data/Model/model.json'

### ISSUE THREAD

**Issue by SandorAlbert** [ardamavi/Game-Bot#42]
```
C:\Users\xxx>cd C:\Users\xxx\Desktop\Game-Bot-master\Game-Bot-master

C:\Users\xxx\Desktop\Game-Bot-master\Game-Bot-master>python ai.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "ai.py", line 58, in <module>
    main()
  File "ai.py", line 14, in main
    model_file = open('Data/Model/model.json', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'Data/Model/model.json'

C:\Users\xxx\Desktop\Game-Bot-master\Game-Bot-master>
```
Doesn't initialize a model and cannot import it. Am I missing something?

**Comment by SandorAlbert** [comment]
My bad. Have to "python create_dataset.py" first.
