### ISSUE TITLE
Key not on list

### ISSUE THREAD

**Issue by ardittristan** [ardamavi/Game-Bot#7]
After finally getting create dataset to actually run by updating python to 3.6.1 it now gives me the error that any key I press is not in the list.

https://pastebin.com/0vG2RUY9

**Comment by ardamavi** [comment]
I can't open link, can you share again with another method.

**Comment by ardittristan** [comment]
`PS D:\Downloads\Game-Bot-master> py -3 create_dataset.py
Using TensorFlow backend.
Using TensorFlow backend.
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Ardit\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "C:\Users\Ardit\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Downloads\Game-Bot-master\create_dataset.py", line 48, in listen_mouse
    with mouse_listener(on_move=on_move, on_click=on_click, on_scroll=on_scroll) as listener:
NameError: name 'on_move' is not defined
Traceback (most recent call last):
  File "create_dataset.py", line 76, in <module>
    main()
  File "create_dataset.py", line 72, in main
    listen_keyboard()
  File "create_dataset.py", line 63, in listen_keyboard
    listener.join()
  File "C:\Users\Ardit\AppData\Local\Programs\Python\Python36\lib\site-packages\pynput\_util\__init__.py", line 199, in join
    six.reraise(exc_type, exc_value, exc_traceback)
  File "C:\Users\Ardit\AppData\Local\Programs\Python\Python36\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Ardit\AppData\Local\Programs\Python\Python36\lib\site-packages\pynput\_util\__init__.py", line 154, in inner
    return f(self, *args, **kwargs)
  File "C:\Users\Ardit\AppData\Local\Programs\Python\Python36\lib\site-packages\pynput\keyboard\_win32.py", line 237, in _process
    self.on_press(key)
  File "C:\Users\Ardit\AppData\Local\Programs\Python\Python36\lib\site-packages\pynput\_util\__init__.py", line 75, in inner
    if f(*args) is False:
  File "create_dataset.py", line 57, in on_press
    save_event_keyboard(data_path, 1, key)
  File "create_dataset.py", line 25, in save_event_keyboard
    key = get_id(key)
  File "D:\Downloads\Game-Bot-master\game_control.py", line 13, in get_id
    return get_keys().index(key)
ValueError: 'g' is not in list
PS D:\Downloads\Game-Bot-master>`

**Comment by ardamavi** [comment]
'g' is included in the list.
Could it contain special characters?
You can write the [`get_id()`](https://github.com/ardamavi/Game-Bot/blob/master/game_control.py#L12) inputs to text file and control it with `vim` editor?

**Comment by ardittristan** [comment]
my game_control.py is the same as the one on github, I did not edit anything, and I can see it in the get_keys() list. I don't know how vim works.

**Comment by ardamavi** [comment]
You can share text file with me.

**Comment by Remie9** [comment]
Hi Im getting same issue it cannot find the key...
