### ISSUE TITLE
on_move not defined

### ISSUE THREAD

**Issue by yawikflame** [ardamavi/Game-Bot#8]
my git bash window shows this after installing the requirements...
```
$ python create_dataset.py
Using TensorFlow backend.
Process Process-1:
Traceback (most recent call last):
  File "C:\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\yawik\Downloads\Game-Bot\create_dataset.py", line 48, in listen_mouse
    with mouse_listener(on_move=on_move, on_click=on_click, on_scroll=on_scroll) as listener:
NameError: name 'on_move' is not defined
```
good luck and thanks for sharing!

**Comment by ardamavi** [comment]
Fixed with new commit: [50d61ac](https://github.com/ardamavi/Game-Bot/tree/50d61accd6850640ef71cb832fcfd95c2f19b64b)
