### ISSUE TITLE
ValueError: 'arr' does not have a suitable array shape for any mode.

### ISSUE THREAD

**Issue by yawikflame** [ardamavi/Game-Bot#9]
```
$ python create_dataset.py
Using TensorFlow backend.
Unhandled exception in listener callback
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\pynput\_util\win32.py", line 375, in _handler
    converted = self._convert(code, msg, lpdata)
  File "C:\Python37\lib\site-packages\pynput\_util\win32.py", line 390, in _convert
    raise NotImplementedError()
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\pynput\_util\__init__.py", line 157, in inner
    return f(self, *args, **kwargs)
  File "C:\Python37\lib\site-packages\pynput\_util\win32.py", line 379, in _handler
    self._handle(code, msg, lpdata)
  File "C:\Python37\lib\site-packages\pynput\mouse\_win32.py", line 190, in _handle
    self.on_click(data.pt.x, data.pt.y, button, pressed)
  File "C:\Python37\lib\site-packages\pynput\_util\__init__.py", line 78, in inner
    if f(*args) is False:
  File "C:\Users\yawik\Downloads\Game-Bot\create_dataset.py", line 43, in on_click
    save_event_mouse(data_path, x, y)
  File "C:\Users\yawik\Downloads\Game-Bot\create_dataset.py", line 34, in save_event_mouse
    save_img(data_path, screenshot)
  File "C:\Users\yawik\Downloads\Game-Bot\get_dataset.py", line 15, in save_img
    imsave(path, img)
  File "C:\Python37\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "C:\Python37\lib\site-packages\scipy\misc\pilutil.py", line 217, in imsave
    im = toimage(arr, channel_axis=2)
  File "C:\Python37\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "C:\Python37\lib\site-packages\scipy\misc\pilutil.py", line 327, in toimage
    raise ValueError("'arr' does not have a suitable array shape for "
ValueError: 'arr' does not have a suitable array shape for any mode.
Process Process-1:
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\pynput\_util\win32.py", line 375, in _handler
    converted = self._convert(code, msg, lpdata)
  File "C:\Python37\lib\site-packages\pynput\_util\win32.py", line 390, in _convert
    raise NotImplementedError()
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\yawik\Downloads\Game-Bot\create_dataset.py", line 52, in listen_mouse
    listener.join()
  File "C:\Python37\lib\site-packages\pynput\_util\__init__.py", line 205, in join
    six.reraise(exc_type, exc_value, exc_traceback)
  File "C:\Python37\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "C:\Python37\lib\site-packages\pynput\_util\__init__.py", line 157, in inner
    return f(self, *args, **kwargs)
  File "C:\Python37\lib\site-packages\pynput\_util\win32.py", line 379, in _handler
    self._handle(code, msg, lpdata)
  File "C:\Python37\lib\site-packages\pynput\mouse\_win32.py", line 190, in _handle
    self.on_click(data.pt.x, data.pt.y, button, pressed)
  File "C:\Python37\lib\site-packages\pynput\_util\__init__.py", line 78, in inner
    if f(*args) is False:
  File "C:\Users\yawik\Downloads\Game-Bot\create_dataset.py", line 43, in on_click
    save_event_mouse(data_path, x, y)
  File "C:\Users\yawik\Downloads\Game-Bot\create_dataset.py", line 34, in save_event_mouse
    save_img(data_path, screenshot)
  File "C:\Users\yawik\Downloads\Game-Bot\get_dataset.py", line 15, in save_img
    imsave(path, img)
  File "C:\Python37\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "C:\Python37\lib\site-packages\scipy\misc\pilutil.py", line 217, in imsave
    im = toimage(arr, channel_axis=2)
  File "C:\Python37\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "C:\Python37\lib\site-packages\scipy\misc\pilutil.py", line 327, in toimage
    raise ValueError("'arr' does not have a suitable array shape for "
ValueError: 'arr' does not have a suitable array shape for any mode.
```
tried running it after the last fix...getting this now :/
i really want this to work!

**Comment by ardamavi** [comment]
Can you check 'save_img' function's 'screensshot' input?

**Comment by yawikflame** [comment]
you mean debug the program? not sure how i can check the input 😅
we can discord(like skype) if you'd like so you can see exactly what i'm
doing...
if you have time this weekend or something..

**Comment by kawal7415** [comment]
I know what is the error:

Open file get_dataset.py and go to line 15

change from **imsave(path, img)** to **imsave(img, path)** 



My discord account is kawal.52925#2272

**Comment by yawikflame** [comment]
added you on discord.
now getting this error:
https://pastebin.com/c0E23EWJ

cheers,
yawik

**Comment by Remie9** [comment]
change the imsave but got this error now:

  File "C:\Users\Jeremie\AppData\Roaming\Python\Python36\site-packages\PIL\Image.py", line 1989, in save
    raise ValueError('unknown file extension: {}'.format(ext))
ValueError: unknown file extension:

**Comment by rodizipa** [comment]
I would suggest replacing imsave and imread to imageio lib correspondent functions as suggested by scipy docs as the scipy.misc image related functions are deprecated. (It also gives a suggestion to replace imageresize)

**Comment by yarodevuci** [comment]
did anyone had any luck with this?!

**Comment by lvchp** [comment]
I have the same problem.
Do you have new updates on this issue?

**Comment by ardamavi** [comment]
I am too busy at these times, I cannot support this project.

**Comment by lvchp** [comment]
> I am too busy at these times, I cannot support this project.

This is a good project, I hope it will be updated soon

**Comment by caretbay47** [comment]
Um so when u change the imsave(path, img) to imsave(img, path) it now doesnt know what format u want the img to be... as im currently debugging this code... i used imsave(img + '.jpg', path) and that seems to work but im not sure if this is the proper fix...ive also resorted to using imageio.imsave(img + '.jpg', path)
